--
-- TABLESAMPLE TEST
--

CREATE TABLE sample (id INT, name text);

INSERT INTO sample VALUES (1, 'victor');
INSERT INTO sample VALUES (2, 'peter');
INSERT INTO sample VALUES (3, 'james');
INSERT INTO sample VALUES (4, 'paul');
INSERT INTO sample VALUES (5, 'kate');
INSERT INTO sample VALUES (6, 'jane');
INSERT INTO sample VALUES (7, 'samual');
INSERT INTO sample VALUES (8, 'david');
INSERT INTO sample VALUES (9, 'job');
INSERT INTO sample VALUES (10, 'neil');
INSERT INTO sample VALUES (11, 'victor');
INSERT INTO sample VALUES (12, 'peter');
INSERT INTO sample VALUES (13, 'james');
INSERT INTO sample VALUES (14, 'paul');
INSERT INTO sample VALUES (15, 'kate');
INSERT INTO sample VALUES (16, 'jane');
INSERT INTO sample VALUES (17, 'samual');
INSERT INTO sample VALUES (18, 'david');
INSERT INTO sample VALUES (19, 'job');
INSERT INTO sample VALUES (20, 'neil');

ANALYZE sample;

SELECT * FROM sample TABLESAMPLE SYSTEM (60) REPEATABLE (10);

SELECT * FROM sample TABLESAMPLE BERNOULLI (70) REPEATABLE (11);

SELECT * FROM sample TABLESAMPLE BERNOULLI (70) REPEATABLE (11);

SELECT * FROM sample TABLESAMPLE BERNOULLI (70) REPEATABLE (19);

SELECT * FROM sample TABLESAMPLE BERNOULLI (7) REPEATABLE (19);

SELECT * FROM sample TABLESAMPLE BERNOULLI (1) REPEATABLE (19);

SELECT * FROM sample TABLESAMPLE SYSTEM (65) REPEATABLE (20);

SELECT * FROM sample TABLESAMPLE SYSTEM (65) REPEATABLE (2);

SELECT * FROM sample TABLESAMPLE SYSTEM (65) REPEATABLE (20);

SELECT * FROM sample TABLESAMPLE BERNOULLI (70) REPEATABLE (11) order by id limit 5;

SELECT * INTO tmp FROM sample TABLESAMPLE BERNOULLI (4);

DROP TABLE tmp;

SELECT * INTO tmp FROM sample TABLESAMPLE SYSTEM (20);

DROP TABLE tmp;

DROP TABLE sample;
